### ISSUE TITLE
could not determine executable to run

### ISSUE THREAD

**Issue by mix1009** [heltonteixeira/openrouterai#2]
when I run
$ npx @mcpservers/openrouterai
npm error could not determine executable to run

comparing package.json with other mcpservers,
"bin" is missing.

**Comment by heltonteixeira** [comment]
'bin' is only needed when installed globally
But that was a good catch, the package.json is indeed missing some key sections.
Thanks for that.

**Comment by mix1009** [comment]
Thanks for the update. It works well.
